### getEmployees
GET http://localhost:3000/api/employees
###

### createEmployee
POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "name": "David",
  "position": "Junior",
  "office": "Marbella",
  "salary": "20000"
}
###

### getEmployee
GET http://localhost:3000/api/employees/6119c0c30e8b377b1b27b
###

### deleteEmployee
DELETE http://localhost:3000/api/employees/6119c3537fd8a97f28bd2775
###

### updateEmployee
PUT http://localhost:3000/api/employees/6119c0c30e8b377b1b27bf1e
Content-Type: application/json

{
  "name": "Bartolo",
  "position": "Semisenior",
  "office": "Galicia",
  "salary": "26000"
}
###
